In [1]:
import pandas as pd
import uuid

In [6]:
# pip install sqlalchemy

In [2]:
# pip install psycopg2-binary

In [3]:
con = "postgresql://admin:secret@localhost:5432/sourcedb"

In [ ]:
pd.read_sql_query("""
SELECT * FROM information_schema.tables
WHERE table_schema = 'public'
""", con)

In [21]:
df_test = pd.DataFrame([{
    'id': i,
    'uuid': str(uuid.uuid4())
} for i in range(10)])
df_test

   id                                  uuid
0   0  5039f86c-379a-462a-a8c5-a7195f9ed43e
1   1  e58a4d31-3dde-4435-8eb9-375642eb238f
2   2  2fb18656-b37e-44ea-be63-daedb0248def
3   3  d5a9d0da-ce82-447a-b764-b3ad028fc300
4   4  a458cc4c-b2cb-4a81-a9c0-49eb79f03fa5
5   5  f56762ca-60b5-4486-8f21-2ead00932a3a
6   6  e1ce5f1c-f725-4fee-b528-bdbc1326aaa4
7   7  35395f82-ada9-49f7-b261-5e95c8725996
8   8  ed220d84-cbb8-4354-ae4b-04d897772ae0
9   9  607f8935-0553-4dc9-910a-3e42db5377b6

In [23]:
df_test.to_sql('mapping_id', con, index=False, if_exists='replace')

10

In [28]:
# oracle

In [31]:
# pip install oracledb

In [9]:
# pip install faker

In [10]:
from urllib.parse import quote_plus
import faker

In [107]:
con_oracle = "oracle+oracledb://SYSTEM:password@localhost:1521/FREE"
# con_oracle = f"oracle+oracledb://c##dbzuser:{quote_plus('apppassword')}@localhost:1521/?service_name=FREE"

In [108]:
pd.read_sql_query("""
SELECT *
FROM 
all_tables
--user_tables
-- WHERE owner = 'C##APPUSER'
""", con_oracle)

,owner,table_name,tablespace_name,cluster_name,iot_name,status,pct_free,pct_used,ini_trans,max_trans,...,memoptimize_read,memoptimize_write,has_sensitive_column,admit_null,data_link_dml_enabled,logical_replication,staging,row_change_tracking,has_reservable_column,vector_index_type
0,SYS,TS$,SYSTEM,C_TS#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
1,SYS,ICOL$,SYSTEM,C_OBJ#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2,SYS,USER$,SYSTEM,C_USER#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,YES,NO,NO,ENABLED,NO,NO,NO,None
3,SYS,CDEF$,SYSTEM,C_COBJ#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
4,SYS,CCOL$,SYSTEM,C_COBJ#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2519,DVSYS,REALM_ID_TAB,SYSAUX,NaN,NaN,VALID,10.0,NaN,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2520,DVSYS,COMMAND_RULE_ID_TAB,SYSAUX,NaN,NaN,VALID,10.0,NaN,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2521,DVSYS,RULE_SET_ID_TAB,SYSAUX,NaN,NaN,VALID,10.0,NaN,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2522,SYS,DBMS_SQLPATCH_STATE,SYSTEM,NaN,NaN,VALID,10.0,40.0,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2523,SYS,DBMS_SQLPATCH_FILES,SYSTEM,NaN,NaN,VALID,10.0,40.0,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None

In [110]:
pd.read_sql_query("""
SELECT * FROM C##APPUSER.CUSTOMERS
""", con_oracle)

   id       name             email
0   1  Test User  test@example.com

In [11]:
f = faker.Faker()

In [12]:
f.email()

'eric61@example.net'

In [23]:
df1 = pd.DataFrame([{
    'name': f.name(),
    'email': f.email()
} for i in range(10)])
df1

                  name                         email
0   Christopher Nelson  kennedykatherine@example.com
1   Christopher George       katherine73@example.org
2      Joy Hancock PhD       robertfoley@example.org
3        Chelsea Lopez          hgriffin@example.org
4       Jessica Watson           ophelps@example.com
5         Joshua Stark      hughesashley@example.net
6           Cory Downs     johnsonedward@example.com
7         Laura Harvey       tarasanchez@example.com
8  Christopher Collins            ivan10@example.com
9      Elizabeth Black          daniel03@example.org

In [114]:
df1.to_sql(name='CUSTOMERS', con=con_oracle, schema='C##APPUSER', index=False, if_exists='append')

/var/folders/g8/mw5d7clj68s72lxq_1wxm3f00000gn/T/ipykernel_1314/3317157004.py:1: UserWarning: The provided table name 'CUSTOMERS' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df1.to_sql(name='CUSTOMERS', con=con_oracle, schema='C##APPUSER', index=False, if_exists='append')

-1

In [115]:
pd.read_sql_query("""
SELECT * FROM C##APPUSER.CUSTOMERS
""", con_oracle)

    id              name                       email
0   21     Robin Herrera       kenneth37@example.org
1   22  Kimberly Cameron      qmccormick@example.org
2   23        Janice Lam       colleen23@example.org
3   24   Shelia Martinez  jameshenderson@example.org
4   25   Cassidy Jenkins          cmarks@example.net
5   26      Robin Obrien   sarahhamilton@example.net
6   27     Richard Moore       wmartinez@example.org
7   28      Aaron Jordan       hudsonzoe@example.net
8   29       Shawn Mcgee        psanchez@example.com
9   30       Susan Chang          john66@example.org
10   1         Test User            test@example.com

# Mssql

In [24]:
con_mssql = "mssql+pymssql://sa:YourStrong!Passw0rd@localhost:1433/sourcedb"

In [25]:
pd.read_sql_query("""
SELECT *
FROM sys.tables
""", con_mssql)

,name,object_id,principal_id,schema_id,parent_object_id,type,type_desc,create_date,modify_date,is_ms_shipped,...,history_retention_period_unit_desc,is_node,is_edge,data_retention_period,data_retention_period_unit,data_retention_period_unit_desc,ledger_type,ledger_type_desc,ledger_view_id,is_dropped_ledger_table
0,systranschemas,901578250,None,1,0,U,USER_TABLE,2026-06-22 07:11:46.200,2026-06-22 07:11:46.260,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
1,change_tables,933578364,None,5,0,U,USER_TABLE,2026-06-22 07:11:46.260,2026-06-22 07:11:46.273,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
2,ddl_history,981578535,None,5,0,U,USER_TABLE,2026-06-22 07:11:46.260,2026-06-22 07:11:46.267,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
3,lsn_time_mapping,1013578649,None,5,0,U,USER_TABLE,2026-06-22 07:11:46.260,2026-06-22 07:11:46.270,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
4,captured_columns,1045578763,None,5,0,U,USER_TABLE,2026-06-22 07:11:46.260,2026-06-22 07:11:46.267,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
5,index_columns,1077578877,None,5,0,U,USER_TABLE,2026-06-22 07:11:46.260,2026-06-22 07:11:46.267,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
6,customers,1253579504,None,1,0,U,USER_TABLE,2026-06-22 07:11:46.433,2026-06-22 07:11:47.077,False,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False
7,dbo_customers_CT,1285579618,None,5,0,U,USER_TABLE,2026-06-22 07:11:46.780,2026-06-22 07:11:46.797,True,...,None,False,False,-1,-1,INFINITE,0,NON_LEDGER_TABLE,None,False

In [26]:
pd.read_sql_query("""
SELECT * FROM customers
""", con_mssql)

   id               name                      email
0   1           Casey Ho     courtney37@example.net
1   2       Susan Watson   loganjeffrey@example.com
2   3   Patricia Mullins     cblanchard@example.net
3   4         Tina Berry   jacobsandrew@example.org
4   5  Elizabeth Aguilar     brownmegan@example.org
5   6  Jennifer Reynolds  raymondmartin@example.com
6   7     Chelsea Brooks       vhammond@example.org
7   8     Andre Holloway    briangibson@example.com
8   9       Ashley Mckay    wigginsjohn@example.org
9  10      Barbara Perry       travis08@example.org

In [27]:
df1.to_sql(name='customers', con=con_mssql, if_exists='append', index=False)

10

In [28]:
pd.read_sql_query("""
SELECT * FROM customers
""", con_mssql)

      id                 name                         email
0      1             Casey Ho        courtney37@example.net
1      2         Susan Watson      loganjeffrey@example.com
2      3     Patricia Mullins        cblanchard@example.net
3      4           Tina Berry      jacobsandrew@example.org
4      5    Elizabeth Aguilar        brownmegan@example.org
5      6    Jennifer Reynolds     raymondmartin@example.com
6      7       Chelsea Brooks          vhammond@example.org
7      8       Andre Holloway       briangibson@example.com
8      9         Ashley Mckay       wigginsjohn@example.org
9     10        Barbara Perry          travis08@example.org
10  1002   Christopher Nelson  kennedykatherine@example.com
11  1003   Christopher George       katherine73@example.org
12  1004      Joy Hancock PhD       robertfoley@example.org
13  1005        Chelsea Lopez          hgriffin@example.org
14  1006       Jessica Watson           ophelps@example.com
15  1007         Joshua Stark      hughesashley@example.net
16  1008           Cory Downs     johnsonedward@example.com
17  1009         Laura Harvey       tarasanchez@example.com
18  1010  Christopher Collins            ivan10@example.com
19  1011      Elizabeth Black          daniel03@example.org