In [20]:
import pandas as pd
import uuid

In [13]:
# pip install psycopg2-binary

In [14]:
con = "postgresql://admin:secret@localhost:5432/sourcedb"

In [16]:
pd.read_sql_query("""
SELECT * FROM information_schema.tables
WHERE table_schema = 'public'
""", con)

Empty DataFrame
Columns: [table_catalog, table_schema, table_name, table_type, self_referencing_column_name, reference_generation, user_defined_type_catalog, user_defined_type_schema, user_defined_type_name, is_insertable_into, is_typed, commit_action]
Index: []

In [21]:
df_test = pd.DataFrame([{
    'id': i,
    'uuid': str(uuid.uuid4())
} for i in range(10)])
df_test

   id                                  uuid
0   0  5039f86c-379a-462a-a8c5-a7195f9ed43e
1   1  e58a4d31-3dde-4435-8eb9-375642eb238f
2   2  2fb18656-b37e-44ea-be63-daedb0248def
3   3  d5a9d0da-ce82-447a-b764-b3ad028fc300
4   4  a458cc4c-b2cb-4a81-a9c0-49eb79f03fa5
5   5  f56762ca-60b5-4486-8f21-2ead00932a3a
6   6  e1ce5f1c-f725-4fee-b528-bdbc1326aaa4
7   7  35395f82-ada9-49f7-b261-5e95c8725996
8   8  ed220d84-cbb8-4354-ae4b-04d897772ae0
9   9  607f8935-0553-4dc9-910a-3e42db5377b6

In [23]:
df_test.to_sql('mapping_id', con, index=False, if_exists='replace')

10

In [28]:
# oracle

In [31]:
# pip install oracledb

In [65]:
# pip install faker

In [66]:
from urllib.parse import quote_plus
import faker

In [107]:
con_oracle = "oracle+oracledb://SYSTEM:password@localhost:1521/FREE"
# con_oracle = f"oracle+oracledb://c##dbzuser:{quote_plus('apppassword')}@localhost:1521/?service_name=FREE"

In [108]:
pd.read_sql_query("""
SELECT *
FROM 
all_tables
--user_tables
-- WHERE owner = 'C##APPUSER'
""", con_oracle)

,owner,table_name,tablespace_name,cluster_name,iot_name,status,pct_free,pct_used,ini_trans,max_trans,...,memoptimize_read,memoptimize_write,has_sensitive_column,admit_null,data_link_dml_enabled,logical_replication,staging,row_change_tracking,has_reservable_column,vector_index_type
0,SYS,TS$,SYSTEM,C_TS#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
1,SYS,ICOL$,SYSTEM,C_OBJ#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2,SYS,USER$,SYSTEM,C_USER#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,YES,NO,NO,ENABLED,NO,NO,NO,None
3,SYS,CDEF$,SYSTEM,C_COBJ#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
4,SYS,CCOL$,SYSTEM,C_COBJ#,NaN,VALID,0.0,0.0,0.0,0.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2519,DVSYS,REALM_ID_TAB,SYSAUX,NaN,NaN,VALID,10.0,NaN,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2520,DVSYS,COMMAND_RULE_ID_TAB,SYSAUX,NaN,NaN,VALID,10.0,NaN,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2521,DVSYS,RULE_SET_ID_TAB,SYSAUX,NaN,NaN,VALID,10.0,NaN,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2522,SYS,DBMS_SQLPATCH_STATE,SYSTEM,NaN,NaN,VALID,10.0,40.0,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None
2523,SYS,DBMS_SQLPATCH_FILES,SYSTEM,NaN,NaN,VALID,10.0,40.0,1.0,255.0,...,DISABLED,DISABLED,NO,NO,NO,ENABLED,NO,NO,NO,None

In [110]:
pd.read_sql_query("""
SELECT * FROM C##APPUSER.CUSTOMERS
""", con_oracle)

   id       name             email
0   1  Test User  test@example.com

In [111]:
f = faker.Faker()

In [112]:
f.email()

'kellynorris@example.net'

In [113]:
df1 = pd.DataFrame([{
    'name': f.name(),
    'email': f.email()
} for i in range(10)])
df1

               name                       email
0     Robin Herrera       kenneth37@example.org
1  Kimberly Cameron      qmccormick@example.org
2        Janice Lam       colleen23@example.org
3   Shelia Martinez  jameshenderson@example.org
4   Cassidy Jenkins          cmarks@example.net
5      Robin Obrien   sarahhamilton@example.net
6     Richard Moore       wmartinez@example.org
7      Aaron Jordan       hudsonzoe@example.net
8       Shawn Mcgee        psanchez@example.com
9       Susan Chang          john66@example.org

In [114]:
df1.to_sql(name='CUSTOMERS', con=con_oracle, schema='C##APPUSER', index=False, if_exists='append')

/var/folders/g8/mw5d7clj68s72lxq_1wxm3f00000gn/T/ipykernel_1314/3317157004.py:1: UserWarning: The provided table name 'CUSTOMERS' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df1.to_sql(name='CUSTOMERS', con=con_oracle, schema='C##APPUSER', index=False, if_exists='append')

-1

In [115]:
pd.read_sql_query("""
SELECT * FROM C##APPUSER.CUSTOMERS
""", con_oracle)

    id              name                       email
0   21     Robin Herrera       kenneth37@example.org
1   22  Kimberly Cameron      qmccormick@example.org
2   23        Janice Lam       colleen23@example.org
3   24   Shelia Martinez  jameshenderson@example.org
4   25   Cassidy Jenkins          cmarks@example.net
5   26      Robin Obrien   sarahhamilton@example.net
6   27     Richard Moore       wmartinez@example.org
7   28      Aaron Jordan       hudsonzoe@example.net
8   29       Shawn Mcgee        psanchez@example.com
9   30       Susan Chang          john66@example.org
10   1         Test User            test@example.com